# -*- coding: utf-8 -*-
"""01 Email Spam Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4lKYSC49sLInH4nVO7DgJiEmDjS0kas

#Task 1: Email Spam Classification
## Objective
Build a machine learning model to classify emails as spam or ham (not spam) using a labeled dataset.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""## Step 1: Data Loading & Exploration

>  Loaded dataset mail_data.csv using Pandas.

> Checked for null values and replaced them with empty strings.

> Converted all text messages to lowercase and stripped extra spaces for consistency.

> Inspected dataset structure and unique labels (ham, spam).
"""

# from google.colab import files
# uploaded = files.upload()


df = pd.read_csv('mail_data.csv')

df.head()

df.isnull().sum()

data = df.where((pd.notnull(df)),'')
data['Message'] = data['Message'].str.strip().str.lower()

data.info()

data['Category'].unique()

"""## Step 2: Data Preprocessing

Used Label Encoding to convert text labels into numeric values:

> ham → 0

> spam → 1

Extracted features (Message) and labels (Category).

Split dataset into training (80%) and testing (20%) sets.
"""

le = LabelEncoder()
# ham = > 0
# spam => 1
data['Category'] = le.fit_transform(data['Category'])

X = data['Message']
Y = data['Category']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

"""## Step 3: Feature Extraction

> Applied TF-IDF Vectorizer to transform email text into numerical features.

> Removed stopwords and ensured all text was lowercased.
"""

feature_extraction = TfidfVectorizer(min_df = 1, stop_words='english', lowercase=True)

X_train_features = feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

"""## Step 4: Model Training

> Chose Logistic Regression as the baseline model.

> Trained the model on the TF-IDF features of training data.
"""

model = LogisticRegression(max_iter=1000)
model.fit(X_train_features, Y_train)

# saving the model.
import pickle
filename = '/content/drive/MyDrive/01 Machine Learning/Internship/Arch Tech/TASK/spam_model.sav'
pickle.dump(model, open(filename, 'wb'))

X_train_pred = model.predict(X_train_features)
train_acc = accuracy_score(Y_train, X_train_pred)
print(train_acc)

X_test_pred = model.predict(X_test_features)
test_acc = accuracy_score(Y_test, X_test_pred)
print("Test Accuracy:", test_acc)

"""## Step 5: Model Evaluation

> Calculated accuracy on both training and testing sets.

> Generated classification report with precision, recall, and F1-score.

> Plotted a confusion matrix heatmap for better visualization of performance
"""

from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(Y_test, X_test_pred))
sns.heatmap(confusion_matrix(Y_test, X_test_pred), annot=True, fmt='d')
plt.show()

"""## Step 6: Prediction on New Data

> Allowed testing with new unseen emails.
m
"""

mail = [input("Enter mail : ")]

pred_input_mail = feature_extraction.transform(mail)

prediction = model.predict(pred_input_mail)
print(prediction)


print(mail, '\n Mail is == ','HAM' if prediction[0]==0 else 'SPAM')

